apiVersion: v1
kind: Secret
metadata:
  name: talos-etcd-s3-keys
  namespace: kube-system
  accessKeyId: YourKeyID # change me - base 64 encoded AWS access key ID
  secretAccessKey: YourKey # change me - base64 encoded AWS secret access key
  resticKey: YourEncKey # change me - base64 encoded encryption key (generate randomly)
  bucketName: "s3:your-bucket-url" # change me - prefix your bucket URL with s3:
                                   # e.g. s3:https://s3.eu-west-2.amazonaws.com/example-bucket
type: Opaque